name: Demo page CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install packages
      run: npm install --if-present
      working-directory: demo/
      
    - name: Build demo
      run: npm run build --if-present
      working-directory: demo/
      
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.2
      with:
        # Build directory to deploy
        build_dir: demo/public/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
